name: demos
type: php:7.2
build:
    flavor: none

size: S

#dependencies:
#    nodejs: # Specify one NPM package per line.
#        reveal: '*'

web:
    commands:
        start: sleep infinity
    locations: 
        "/":
            root: "app"
            index: 
                - "index.html"
            expires: 300s
            scripts: false

disk: 256

hooks:
    build: |
        wget https://github.com/hakimel/reveal.js/archive/3.7.0.tar.gz
        tar zxvf 3.7.0.tar.gz    
