name: demos
type: php:7.2
build:
    flavor: none

size: S

web:
    commands:
        start: sleep infinity
    locations: 
        "/":
            root: "web"
            index: 
                - "index.html"
            expires: 300s
            scripts: false

disk: 256

hooks:
    build: |
        set -e
