name: demos
type: php:7.2
build:
    flavor: none

size: S

web:
    commands:
        start: sleep infinity
    locations:
        "/.well-known":
            root: "web/.well-known"
            rules:
                "apple-app-site-association":
                    headers:
                        Content-Type: application/json
        "/":
            root: "web"
            index:
                - "index.html"
            expires: 300s
            scripts: false

disk: 256

hooks:
    build: |
        curl -sS https://platform.sh/cli/installer | php
        set -e

crons:
    renewcert:
        # Force a redeploy at 10 am (UTC) on the 1st and 15th of every month.
        spec: '0 10 1,15 * *'
        cmd: |
            if [ "$PLATFORM_BRANCH" = master ]; then
                platform redeploy --yes --no-wait
            fi
