name: demos
type: php:7.2
build:
    flavor: none

size: S

web:
    commands:
        start: sleep infinity
    locations: 
        "/":
            root: "web"
            index: 
                - "index.html"
            expires: 300s
            scripts: false

disk: 256

hooks:
    build: |
        curl -sS https://platform.sh/cli/installer | php
        set -e

crons:
    snapshot:
        spec: '0 2 * * 0'
        cmd: |
            if [ "$PLATFORM_BRANCH" = master ]; then
                platform snapshot:create --yes --no-wait
            fi